---
# Install and config grub

- name: Pacstrap grub and os-prober
  command: /usr/bin/pacstrap /mnt grub os-prober

- name: Generate ramdisk
  command: /usr/bin/arch-chroot /mnt /bin/mkinitcpio -p linux chdir=/boot

- name: Run grub install
  command: "/usr/bin/arch-chroot /mnt /bin/grub-install --target=i386-pc --recheck {{ device.name }}"

# - name: Mount windows boot partition
#   command: "/usr/bin/arch-chroot /mnt /usr/bin/mount {{ device.windows }} /mnt"

- name: Generate grub.cfg
  command: /usr/bin/arch-chroot /mnt /bin/grub-mkconfig -o /boot/grub/grub.cfg

# - name: Check if Windows was recognised
#   command: os-prober
#   register: osprober

# - name: Debug os-prober
#   debug: 
#     msg:
#       - "stdout: {{ osprober.stdout }}"
#       - "stderr: {{ osprober.stderr }}"

# - name: Umount windows boot partition
#   command: "/usr/bin/arch-chroot /mnt /usr/bin/umount /mnt"
