---
# /etc configuration

- name: Grant %wheel sudo rights
  lineinfile:
    path: /etc/sudoers
    state: present
    regex: '%wheel\sALL=\(ALL\)\sALL'
    line: '%wheel ALL=(ALL) ALL'

- name: Config ALSA
  copy:
    src: files/thinkpad-t440.conf
    dest: /etc/modeprobe.d/thinkpad-t440.conf
    mode: 0644
  
