---
# Playbook with roles

- hosts: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
#      encrypt: "sha512_crypt"
  become: yes
  become_user: root
  vars_files: ./vars/main.yaml
  roles:
    - role: custom_setup
    - role: etckeeper
      when: hostvars['localhost'].ansible_local['kf-custom']['etckeepersetup'] == "false"
    - role: software

## - name: post installation steps
#- hosts: localhost
#  #  vars_file: ../vars/param.yaml 
#  vars_prompt:
#    - name: "ansible_become_pass"
#      prompt: "Sudo password"
#      private: yes
##      encrypt: "sha512_crypt"
#  become: yes
#  become_user: root
#  roles:
#    role: custom_setup
#
#
#
#- name: the rest
#  tasks:
#
#    - name: install fonts etckeeper
#      pacman:
#        name: ttf-dejavu etckeeper
#        state: present
#
#    - name: install google-chrome
#      pacman:
#        name: google-chrome
#        state: present
#
#    - name: create /data directory
#      file:
#        path: /data
#        state: directory
#        mode: 0755
