- name: post installation steps
  user: root
  hosts: localhost
  #  vars_file: ../vars/param.yaml 
  tasks:

    - name: install fonts
      pacman:
        name: ttf-dejavu
        state: present

    - name: install google-chrome
      pacman:
        name: google-chrome
        state: present
