---
# create a arch linux iso on usb to install arch linux on computer

- hosts: localhost
  become: yes
  vars:
    archlive: /data/archlinux/archlive
    airootfs: "{{ archlive }}/airootfs"
    airootfs_root: "{{ airootfs }}/root"
    airootfs_data: "{{ airootfs }}/data"

  roles:
    - role: create_archlive
      tags: archlive
    - role: cp_files
      tags: copy
    - role: build_iso
      tags: build
