---
# ArchLinux desktop installation

- name: install desktop
  hosts: localhost
  become: yes
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  vars_files: ./vars/main.yaml

  roles:
    - name: Create custom facts like check if etckeeper is installed
      role: custom_setup
      tags: [custom_setup,etckeeper]
    - name: Install and configure etckeeper
      role: etckeeper
      when: hostvars['localhost'].ansible_local['kf-custom']['etckeepersetup'] == "false"
      tags: etckeeper
    - name: Set locale
      role: locale
      tags: locale
    - name: Configure network
      role: network
      tags: network
    - name: Configure /etc
      role: etc_config
      tags: etc_config
    - name: Install standard software packages
      role: install_packages
      tags: inst_std_pkgs
    - name: Battery management
      role: battery
      tags: battery
    - name: Install GUI LXDE
      role: install_gui
      tags: inst_gui
    - name: Create user
      role: adduser
      tags: adduser
    - name: Install from AUR
      role: aur
      tags: aur
    - name: Setup ssh client
      role: ssh_client
      tags: ssh_client
