---
# pacstrap new system

- name: Install new system with pacstrap
  hosts: localhost
  vars_files: ../vars/vars.yml
  tasks:

  - name: Debug
    debug:
      msg: "{{ locale.languages }}"

  - name: Mount new system
    mount:
      src: /dev/sda3 
      path: /mnt
      fstype: ext4
      state: mounted
  
  - name: Install base system using pacstrap
    command: /usr/bin/pacstrap /mnt base ansible git openssh dialog wpa_supplicant intel-ucode grub
  
  - name: Create fstab on new system
    shell: /usr/bin/genfstab -U -p /mnt > /mnt/etc/fstab

  - name: Copy netctl config file
    copy:
      src: /etc/netctl/wlp3s0-AGOG01
      dest: /mnt/etc/netctl

  - name: Enable locales in locale.gen
    replace:
      dest:  /mnt/etc/locale.gen
      regexp: "^#{{ item }}.*$"
      replace: "{{ item }}"
    with_items: locale.languages

  - name: Export locale to locale.conf
    lineinfile:
      dest: /mnt/etc/locale.conf
      line: "LANG={{ item.1.split(' ')[0] }}"
      create: yes
    when: item.0 == 0
    with_indexed_items: locale.languages

  - name: Set keymap
    lineinfile:
      dest: /mnt/etc/vconsole.conf
      line: "KEYMAP={{ locale.keymap }}\nFONT={{ locale.font }}"
      create: yes
    when: locale.keymap is defined and locale.font is defined

  - name: Set timezone
    command: /usr/bin/arch-chroot /mnt ln -sf /usr/share/zoneinfo/{{ locale.timezone }} /etc/localtime

  - name: Generate locale
    command: /usr/bin/arch-chroot /mnt locale-gen

  - name: Generate ramdisk
    command: /usr/bin/arch-chroot /mnt /bin/mkinitcpio -p linux chdir=/boot

  - name: Run grub install
    command: /usr/bin/arch-chroot /mnt /bin/grub-install --target=i386-pc --recheck /dev/sda

  - name: Generate grub.cfg
    command: /usr/bin/arch-chroot /mnt /bin/grub-mkconfig -o /boot/grub/grub.cfg

  - name: Unmount new system
    mount:
      path: /mnt
      state: unmunted
