---
# Install backlight utility and setup

#- name: Include vars file
#  include_vars:
#    file: ./vars/main.yaml

- name: Upgrade system
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install cups and hplip
  pacman:
    name: cups, cups-pdf, hplip

- name: Enable cups
  systemd:
    name: org.cups.cupsd.service
    enabled: yes
    state: started
