---
# Copy ssh keys

- name: Copy alinshrr ssh keys from root to job
  copy:
    src: /root/.ssh/alinshrr
    dest: /home/job/.ssh
    owner: job
    group: job
    mode: preserve

- name: Copy ssh config from root to job
  copy:
    src: /root/.ssh/config
    dest: /home/job/.ssh/config
    owner: job
    group: job
    mode: preserve
